spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coinsupporter?serverTimezone=UTC
    username: root
    password: 1234
  batch:
    jdbc:
      initialize-schema: always

cloud:
  aws:
    credentials:
      accessKey: 'AWS 계정 ACCESS KEY'
      secretKey: 'AWS 계정 SECRET KEY'
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: ycps3

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/ # 유레카 서버

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error